namespace EmptyFlow.SciterAPI {

    [Flags]
    public enum KeyboardStates : uint { // original name KEYBOARD_STATES
        KEYBOARD_STATE_LSHIFT = 0x0001,
        KEYBOARD_STATE_RSHIFT = 0x0002,
        KEYBOARD_STATE_LCONTROL = 0x0040,
        KEYBOARD_STATE_RCONTROL = 0x0080,
        KEYBOARD_STATE_LALT = 0x0100,
        KEYBOARD_STATE_RALT = 0x0200,
        KEYBOARD_STATE_LCOMMAND = 0x0400,
        KEYBOARD_STATE_RCOMMAND = 0x0800,
        KEYBOARD_STATE_NUM = 0x1000,
        KEYBOARD_STATE_CAPS = 0x2000,
        KEYBOARD_STATE_MODE = 0x4000,

        KEYBOARD_STATE_CONTROL = ( KEYBOARD_STATE_LCONTROL | KEYBOARD_STATE_RCONTROL ),
        KEYBOARD_STATE_SHIFT = ( KEYBOARD_STATE_LSHIFT | KEYBOARD_STATE_RSHIFT ),
        KEYBOARD_STATE_ALT = ( KEYBOARD_STATE_LALT | KEYBOARD_STATE_LALT ),
        KEYBOARD_STATE_COMMAND = ( KEYBOARD_STATE_LCOMMAND | KEYBOARD_STATE_RCOMMAND ), // "command key" on OSX, "win" on Windows
    }

}
